### ISSUE TITLE
dwarfgen build fails as @dwfpic@ isn't replaced in top level Makefile

### ISSUE THREAD

**Issue by meths** [tomhughes/libdwarf#1]
The `@dwfpic@` macro isn't substituted in the top level Makefile as the configure doesn't have the corresponding substitution commands that the libdwarf directory does.

This means that dwarfgen fails to build:
`gcc  -m32 -O3  -march=i686 -fPIC -DPIC -I. -I.../dwarf-20150310 @dwfpic@  -I. -I. -I./../libdwarf -c ./../libdwarf/dwgetopt.c`
`gcc: error: @dwfpic@: No such file or directory`

Not sure if you're happy for the whole project to use PIC or not and there are a number of ways to fix this so I'm not making a PR for this.  I think compilers need to be far older than you want to support not to handle fPIC but I'm also aware that Solaris Studio uses KPIC instead.

**Comment by tomhughes** [comment]
Not sure why you are submitting this here - the upstream for libdwarf is at http://www.prevanders.net/dwarf.html and this is just my private copy.
